name: Metrics

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: josesreyesd

          # ðŸ”¹ Nada de info general
          base: ""

          # ðŸ”¹ Solo lenguajes
          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_languages_priority: java, kotlin, c#, swift, rust, cobol, go, python, typescript, javascript
          plugin_languages_sections: most-used
          plugin_languages_details: percentage
          plugin_languages_limit: 10
          plugin_languages_colors: github
          plugin_languages_indepth: yes

          config_timezone: America/Mexico_City
